import DarkModeSwitcher from '@/components/DarkModeSwitcher'
import Head from 'next/head'
import Link from 'next/link'
import { useRouter } from 'next/router'
import { memo, useMemo } from 'react'
import clsxm from '../utils/clsxm'

type Props = {
  title: string
  children: React.ReactNode
}

const MainLayout: React.FC<Props> = ({ title, children }) => {
  const { pathname } = useRouter()
  const menus: {
    title: string
    href: string
    active: boolean
  }[] = useMemo(() => {
    return [
      {
        title: 'Products',
        href: '/products',
        active: pathname.startsWith('/products')
      },
      {
        title: 'Carts',
        href: '/carts',
        active: pathname.startsWith('/carts')
      }
    ]
  }, [pathname])

  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <div className='grid grid-cols-12 lg:min-h-[100vh]'>
          <div className='col-span-12 lg:col-span-3 xl:col-span-2 bg-indigo-500 dark:bg-theme-6 dark:text-white'>
            <Link href='/' className='flex h-[7rem]'>
              <div className='m-auto text-center text-white'>
                <div className='text-3xl font-semibold'>Dashboard</div>
                <div className='text-sm font-semibold'>Luqni Maulana</div>
                <div className='text-xs font-semibold'>maulana.7jr@gmail.com</div>
              </div>
            </Link>
            <div>
              {menus.map(({ title, href, active }, index) => (
                <Link
                  key={index}
                  href={href}
                  className={clsxm(
                    'block w-full px-4 py-3 text-white',
                    active ? 'bg-indigo-400 dark:bg-theme-7 border-l-4 border-white dark:border-sky-500' : 'hover:bg-gray-50/20 hover:dark:bg-theme-5'
                  )}
                >
                  {title}
                </Link>
              ))}
            </div>
          </div>
          <div className='col-span-12 lg:col-span-9 xl:col-span-10 bg-gray-100 dark:bg-theme-7 h-full'>
            <div className='flex justify-end p-2 md:p-5 bg-white shadow-sm dark:bg-theme-6'>
              <DarkModeSwitcher/>
            </div>
            <div className='p-2 md:p-5'>
              {children}
            </div>
          </div>
        </div>
      </main>
    </>
  )
}

export default memo(MainLayout)
